# Gradle Properties
org.gradle.jvmargs = -Xmx1G
org.gradle.parallel = true

# Loader Properties
# check these on https://lambdaurora.dev/tools/import_quilt.html
minecraft_version = 1.21.1
mappings_build = 3
loader_version = 0.19.5

# Mod Properties
version = 0.2.1
maven_group = gay.lemmaeof
archives_base_name = kdlycontent

# Dependencies
# check on https://lambdaurora.dev/tools/import_quilt.html
fapi_version = 0.116.17
kdl4j_version = 1.0.1
lib39_version = 1.5.0-experimental6.1+1.20.1
staticdata_version=1.1.3+1.21.1
