modLoader = "javafml"
loaderVersion = "[4,)"
license = "BSD-3"
issueTrackerURL = "https://github.com/lemmaeof/kdlycontent/issues"

[[mods]]
modId = "kdlycontent"
version = "${version}"
displayName = "Kdly Content"
description = '''A tool to define new blocks, items, and more statically in kdl.'''
authors = "LemmaEOF"
displayURL = "https://github.com/lemmaeof/kdlycontent"
logoFile = "assets/kdlycontent/icon.png"

[properties]
"connector:placeholder" = true

[[dependencies.kdlycontent]]
modId = "connector"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.kdlycontent]]
modId = "neoforge"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.kdlycontent]]
modId = "minecraft"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.kdlycontent]]
modId = "fabric_api"
type = "required"
versionRange = "*"
ordering = "NONE"
side = "BOTH"

[[dependencies.kdlycontent]]
modId = "staticdata"
mandatory = true
versionRange = "*"
ordering = "NONE"
side = "BOTH"
